apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: myapp  # The namespace where the service will live
spec:
  selector:
    app: backend  # This should match the labels defined in the Deployment
  ports:
    - protocol: TCP
      port: 5000  # Port on which the Service will be exposed
      targetPort: 5000  # Port on which the container is listening
  type: ClusterIP  # Service type, accessible only within the cluster
