apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: myapp  # The namespace where the deployment will live
spec:
  replicas: 1  # Number of instances of the frontend
  selector:
    matchLabels:
      app: frontend  # Label to identify the Pods managed by this Deployment
  template:
    metadata:
      labels:
        app: frontend  # Same label as in the selector
    spec:
      containers:
        - name: frontend  # Name of the container
          image: sdinesh14/frontend-app:latest  # Docker image to use
          ports:
            - containerPort: 89  # Port the container listens on
