apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: myapp  # The namespace where the service will live
spec:
  selector:
    app: frontend  # This should match the labels defined in the Deployment
  ports:
    - protocol: TCP
      port: 80  # Port on which the Service will be exposed
      targetPort: 80  # Port on which the container is listening
  type: LoadBalancer  # Service type, accessible from outside the cluster
